#!/usr/bin/python3
# vim: ts=4 sts=4 sw=4 expandtab

import serial
import time
import argparse
import sys
from progress.bar import Bar

class EEPROMprogrammer:
    def __init__(self, port='/dev/ttyUSB0', quiet=False, verbose=False):
        self.ser = serial.Serial(port=port,
                                 baudrate=9600,
                                 parity=serial.PARITY_NONE,
                                 bytesize=8,
                                 stopbits=serial.STOPBITS_ONE,
                                 timeout=5)
        # Initialize by sending a newline, so we get a ready> prompt.
        self.quiet = quiet
        self.verbose = verbose
        if not self.quiet:
            print('Initializing programmer on port {}'.format(port), file=sys.stderr)
        self.ser.reset_output_buffer()
        self.ser.reset_input_buffer()
        self.ser.write(b'\r')
        self.ser.flush()
        out = self.ser.read_until(b'ready>')
        if out.endswith(b'ready>'):
            # Ensure echo is enabled
            self.ser.write(b'echo on\r')
            self.ser.flush()
            out = self.ser.read_until(b'ready>')
            if out.endswith(b'ready>'):
                if not self.quiet:
                    print("Initialized; echo enabled", file=sys.stderr)
            else:
                raise RuntimeError("Did not receive ready> prompt after enabling echo, got [{}]".format(out))
        else:
            raise RuntimeError("Did not receive ready> prompt, got [{}]".format(out))

    def read(self, start_addr, length):
        if start_addr > 0x7fff:
            raise TypeError("start_addr must be <= 0x7fff")
        end_addr = start_addr + length - 1
        if end_addr > 0x7fff:
            raise TypeError("end_addr must be <= 0x7fff")

        # ready>read 0xa000 0xa003
        # Start addr: a000 (40960)
        # End addr: a003 (40963)
        # Requesting 4 bytes now...
        # 62633233ready>
        read_cmd = "read 0x{:04x} 0x{:04x}\r".format(start_addr, end_addr).encode('UTF-8')
        if self.verbose:
            print("Sending read command: [{}]".format(read_cmd), file=sys.stderr)
        if not args.quiet and not args.verbose:
            progress_bar = Bar('Reading', max=length)
        self.ser.write(read_cmd)
        self.ser.flush()
        self.ser.read_until(b'bytes now...\r\n')
        for cur_addr in range(start_addr, end_addr + 1):
            byte = int(self.ser.read(2), 16)
            if args.verbose:
                print("0x{:04x} {:02x} {}".format(args.address + wrote_bytes, byte, chr(byte) if 32 < byte < 127 else " "), file=sys.stderr)
            if not args.quiet and not args.verbose:
                progress_bar.next()
            yield byte
        if not args.quiet and not args.verbose:
            progress_bar.finish()

    def write(self, start_addr, data, page_mode=True, data_protect=True):
        if start_addr > 0x7fff:
            raise TypeError("start_addr must be <= 0x7fff")
        end_addr = start_addr + len(data) - 1
        if end_addr > 0x7fff:
            raise TypeError("end_addr must be <= 0x7fff")

        # Set page and data protect mode
        self.ser.write('page_write {}\r'.format('on' if page_mode else 'off').encode('UTF-8'))
        self.ser.read_until(b'ready>')
        self.ser.write('eeprom_lock {}\r'.format('on' if data_protect else 'off').encode('UTF-8'))
        self.ser.read_until(b'ready>')

        # --- with paging enabled ---
        # ready>write 0x203e 0x2041
        # Start addr: 203e (8254)
        # End addr: 2041 (8257)
        # Total bytes to write: 4
        # Paging
        # EEPROM Lock Enabled
        # S 2/4
        # W
        # S 2/2
        # W
        # ready>
        #
        # --- with paging disabled ---
        # ready>write 0x203e 0x2041
        # Start addr: 203e (8254)
        # End addr: 2041 (8257)
        # Total bytes to write: 4
        # No Paging
        # EEPROM Lock Enabled
        # S 1/4
        # W
        # S 1/3
        # W
        # S 1/2
        # W
        # S 1/1
        # W
        # ready>

        write_cmd = "write 0x{:04x} 0x{:04x}\r".format(start_addr, end_addr).encode('UTF-8')
        if self.verbose:
            print("Sending write command: [{}]".format(write_cmd), file=sys.stderr)
        self.ser.write(write_cmd)
        self.ser.flush()

        if not args.quiet and not args.verbose:
            progress_bar = Bar('Writing', max=len(data))
        byte_idx = 0
        while True:
            # Wait for "S N/M"
            self.ser.read_until(b'S ')
            page_size = int(self.ser.read_until(b'/').decode().rstrip('/'))
            remaining = int(self.ser.read_until(b'\r\n').decode().rstrip('\r\n'))

            # Send next page_size bytes
            for i in range(page_size):
                if self.verbose:
                    print("0x{:04x}: {:02x}".format(start_addr + byte_idx, data[byte_idx]), file=sys.stderr)
                if not self.quiet and not args.verbose:
                    progress_bar.next()

                self.ser.write(bytes([data[byte_idx]]))
                byte_idx += 1
            self.ser.flush()

            # Wait for "W" prompt
            out1 = self.ser.read_until(b'W\r\n')
            if byte_idx >= len(data):
                break
        if not args.quiet and not args.verbose:
            progress_bar.finish()
        self.ser.read_until(b'ready>')

if __name__== "__main__":
    parser = argparse.ArgumentParser(description="EEPROM programmer")
    parser.add_argument('command', help='Execution mode: read or write EEPROM', choices=('read','write',))
    parser.add_argument('filename', help='Source/dest filename, "-" for STDIN', default='-')
    parser.add_argument('--address', '-a', default='0x0000', type=lambda a: int(a,0), help='Starting EEPROM address, default=0x0000')
    parser.add_argument('--length', '-l', default='0', type=lambda l: int(l,0), help='Number of bytes to read/write, default=0=all')
    parser.add_argument('--verify', action='store_true', default=False, help='Verify written data after writing')
    parser.add_argument('--verbose', '-v', action='store_true', default=False)
    parser.add_argument('--quiet', '-q', action='store_true', default=False)
    parser.add_argument('--port', '-p', default='/dev/ttyUSB0')
    args = parser.parse_args()

    if args.command == 'read':
        programmer = EEPROMprogrammer(verbose=args.verbose, quiet=args.quiet, port=args.port)
        if not args.quiet:
            print("Reading from EEPROM to {}".format(args.filename), file=sys.stderr)
        if args.filename == '-':
            print("Filename must be specified when reading", file=sys.stderr)
            sys.exit(1)
        wrote_bytes=0
        if args.length == 0:
            read_length = 0x7fff - args.address
        else:
            read_length = args.length
        with open(args.filename, 'wb') as fh:
            for byte in programmer.read(args.address, read_length):
                wrote_bytes += fh.write(byte.to_bytes(1, 'little'))
        sys.exit(0)

    if args.command == 'write' or args.command == 'verify':
        programmer = EEPROMprogrammer(verbose=args.verbose, quiet=args.quiet, port=args.port)
        data = b''
        if args.filename == '-':
            data = sys.stdin.buffer.read(-1 if args.length == 0 else args.length)
        else:
            with open(args.filename, "rb") as fh:
                data = fh.read(-1 if args.length == 0 else args.length)

    if args.command == 'write':
        programmer = EEPROMprogrammer(verbose=args.verbose, quiet=args.quiet, port=args.port)
        if not args.quiet:
            print("Writing {} bytes to EEPROM from {}.".format(len(data), args.filename), file=sys.stderr)
        programmer.write(args.address, data)
        if not args.quiet:
            print("Done.")

    if args.command == 'verify' or (args.command == 'write' and args.verify):
        programmer = EEPROMprogrammer(verbose=False, quiet=True, port=args.port)
        if not args.quiet:
            print("Verifying {} bytes".format(len(data)))
        if args.verbose:
            print("ADDR    DATA    EEPROM", file=sys.stderr)
        if not args.quiet and not args.verbose:
            progress_bar = Bar('Verifying', max=len(data))
        data_iter = iter(data)
        data_ok = True
        cur_addr = args.address
        for byte in programmer.read(args.address, len(data)):
            data_byte = next(data_iter)
            if args.verbose:
                print("0x{:04x}: {:02x} {} {} {:02x} {}".format(cur_addr,
                            data_byte, chr(data_byte) if 32 < data_byte < 127 else " ",
                            '==' if data_byte == byte else '!=',
                            byte, chr(byte) if 32 < byte < 127 else " "), file=sys.stderr)
            if byte != data_byte:
                data_ok = False
            cur_addr += 1
            if not args.quiet and not args.verbose:
                progress_bar.next()
        if not args.quiet and not args.verbose:
            progress_bar.finish()
        if not args.quiet:
            if data_ok:
                print("Data verified", file=sys.stderr)
            else:
                print("Data error", file=sys.stderr)
        if not data_ok:
            sys.exit(1)
